#!/usr/bin/env bash
# Generate the deployment-specific, gitignored config files Tektonix needs to
# run. Idempotent: existing files are left untouched, so generated secrets stay
# stable across boots (rotating AUTH_SECRET_KEY would lock out stored 2FA).
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

gen_secret_hex() { python3 -c "import secrets;print(secrets.token_hex(32))"; }
gen_auth_key()   { python3 -c "import base64,secrets;print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())"; }

# One router key shared by the agent and the router; one review secret shared by
# the agent and the two Node review services. Generated once, reused thereafter.
ROUTER_KEY="sk-local-dev-$(python3 -c "import secrets;print(secrets.token_hex(8))")"
REVIEW_SECRET="$(gen_secret_hex)"
AUTH_KEY="$(gen_auth_key)"

if [ ! -f .env ]; then
  cat > .env <<EOF
# Generated by .cursor/gen-config.sh for the Cloud Agent dev environment.
LANGGRAPH_PG_DSN=postgresql://agent:agent@127.0.0.1:5432/three_d_agent
MODEL_ROUTER_URL=http://127.0.0.1:4001/v1
MODEL_ROUTER_KEY=${ROUTER_KEY}
DEFAULT_BUDGET_USD=5.0
API_PORT=8100
LANGSMITH_TRACING=false
LANGSMITH_API_KEY=
LANGSMITH_PROJECT=
LANGCHAIN_OPENAI_STREAM_CHUNK_TIMEOUT_S=30
AUTH_SECRET_KEY=${AUTH_KEY}
ADMIN_EMAIL=admin@example.com
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
REVIEW_CONTROL_SECRET=${REVIEW_SECRET}
# Optional. Set OPENROUTER_API_KEY in services/model-router/.env for live model
# calls; the fallback GitHub token below is optional too.
GITHUB_TOKEN=
EOF
  chmod 600 .env
  echo "wrote .env"
else
  echo ".env exists, leaving it"
fi

# Router credentials. OPENROUTER_API_KEY is injected from the environment when
# present (a Cloud Agent secret); otherwise left blank so the router still
# starts and answers its unauthenticated /health/liveliness probe.
if [ ! -f services/model-router/.env ]; then
  # Reuse the agent's router key so the two always match.
  ROUTER_KEY="$(grep '^MODEL_ROUTER_KEY=' .env | cut -d= -f2-)"
  cat > services/model-router/.env <<EOF
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
MODEL_ROUTER_KEY=${ROUTER_KEY}
EOF
  chmod 600 services/model-router/.env
  echo "wrote services/model-router/.env"
else
  # Keep OPENROUTER_API_KEY in sync if a secret is now available and the file
  # still has an empty value.
  if [ -n "${OPENROUTER_API_KEY:-}" ] && grep -q '^OPENROUTER_API_KEY=$' services/model-router/.env; then
    sed -i "s#^OPENROUTER_API_KEY=\$#OPENROUTER_API_KEY=${OPENROUTER_API_KEY}#" services/model-router/.env
    echo "filled OPENROUTER_API_KEY from environment"
  fi
  echo "services/model-router/.env exists, leaving it"
fi

mkdir -p services/shared
if [ ! -f services/shared/.env ]; then
  REVIEW_SECRET="$(grep '^REVIEW_CONTROL_SECRET=' .env | cut -d= -f2-)"
  printf 'REVIEW_CONTROL_SECRET=%s\n' "${REVIEW_SECRET}" > services/shared/.env
  chmod 600 services/shared/.env
  echo "wrote services/shared/.env"
fi

# The router's model pins are the operator's own file, seeded once from the
# committed example.
[ -f services/model-router/config.yaml ] || cp services/model-router/config.example.yaml services/model-router/config.yaml

# A fresh dev box has no projects onboarded yet. Start empty rather than with
# the example's placeholder paths, which point at directories that do not exist.
[ -f projects.json ] || echo '{"projects": {}}' > projects.json

echo "config generation complete"
