#!/usr/bin/env sh
# First-run setup, then the server. Everything here is idempotent: the bundle
# is meant to survive `docker compose down && up` without the operator having
# to remember which of these steps they already did.
set -eu

state=/app/data
# What the two review services read from this container -- projects.json
# and the review-control secret -- in a volume of their own, so they mount
# nothing else of the agent's. Unset, it is the data directory itself.
shared=${TEKTONIX_SHARED_DIR:-$state}
mkdir -p "$state" "$shared" /app/logs

# 0. Files that moved (2026-09-29). Both used to live in the data volume,
#    which the review services mounted whole and read-only -- along with
#    AUTH_SECRET_KEY and the encrypted first password. Moved once, on the
#    first start after the upgrade; the review services start after this
#    container is healthy, so they never see the gap.
for f in review_control_secret projects.json; do
    if [ "$shared" != "$state" ] && [ -f "$state/$f" ] && [ ! -f "$shared/$f" ]; then
        mv "$state/$f" "$shared/$f"
        echo "[entrypoint] moved $f to the shared volume"
    fi
done

# 1. The signing key. Generated once and kept in the volume rather than in the
#    compose file, so `up` in a fresh checkout does not silently invalidate
#    every existing session -- and so it never lands in the operator's shell
#    history or a committed .env.
if [ -z "${AUTH_SECRET_KEY:-}" ]; then
    if [ ! -f "$state/auth_secret_key" ]; then
        python -c "import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())" \
            > "$state/auth_secret_key"
        chmod 600 "$state/auth_secret_key"
        echo "[entrypoint] generated a new AUTH_SECRET_KEY in the data volume"
    fi
    AUTH_SECRET_KEY=$(cat "$state/auth_secret_key")
    export AUTH_SECRET_KEY
fi

# 1b. The review-control secret. Generated the same way and for the same
#     reason: unset means every merge is refused at the end of a task that has
#     already been paid for (agent/health.py), and the deployment reports
#     itself unhealthy until it is set. Generating it now means it already
#     matches when the review service joins the bundle.
if [ -z "${REVIEW_CONTROL_SECRET:-}" ]; then
    if [ ! -f "$shared/review_control_secret" ]; then
        python -c "import secrets;print(secrets.token_urlsafe(32))" > "$shared/review_control_secret"
        chmod 600 "$shared/review_control_secret"
        echo "[entrypoint] generated a new REVIEW_CONTROL_SECRET in the shared volume"
    fi
    REVIEW_CONTROL_SECRET=$(cat "$shared/review_control_secret")
    export REVIEW_CONTROL_SECRET
fi

# 1c. The database password and router key, generated by postgres's entrypoint
#     wrapper (docker/postgres/init-secrets.sh) into volumes mounted read-only
#     here. An explicit LANGGRAPH_PG_DSN / MODEL_ROUTER_KEY still wins.
if [ -z "${MODEL_ROUTER_KEY:-}" ] && [ -n "${MODEL_ROUTER_KEY_FILE:-}" ]; then
    MODEL_ROUTER_KEY=$(cat "$MODEL_ROUTER_KEY_FILE")
    export MODEL_ROUTER_KEY
fi
if [ -z "${LANGGRAPH_PG_DSN:-}" ] && [ -n "${POSTGRES_PASSWORD_FILE:-}" ]; then
    LANGGRAPH_PG_DSN=$(python -c "
import os, sys, urllib.parse
pw = open(sys.argv[1]).read().strip()
print('postgresql://agent:' + urllib.parse.quote(pw, safe='') + '@postgres:5432/' + os.environ.get('POSTGRES_DB', 'tektonix'))
" "$POSTGRES_PASSWORD_FILE")
    export LANGGRAPH_PG_DSN
fi

# 2. projects.json. The agent needs the file to exist; what is IN it comes from
#    the dashboard's own onboarding, so an empty one is the correct start.
#
#    It lives in the shared volume, not beside the code: the two review
#    services are separate containers that read the same file, and a project
#    onboarded from the dashboard has to be visible to them without a
#    rebuild. Both sides honour AGENT_PROJECTS_JSON.
PROJECTS_FILE=${AGENT_PROJECTS_JSON:-/app/projects.json}
if [ ! -f "$PROJECTS_FILE" ]; then
    mkdir -p "$(dirname "$PROJECTS_FILE")"
    echo '{"projects": {}}' > "$PROJECTS_FILE"
    echo "[entrypoint] created an empty $PROJECTS_FILE -- add projects from Settings"
fi

# 3. Wait for Postgres. compose's depends_on only waits for the container, not
#    for the database inside it, and the agent retries its pool forever rather
#    than failing loudly -- which looks like a hang.
if [ -n "${LANGGRAPH_PG_DSN:-}" ]; then
    i=0
    # The DSN is read from the environment, never pasted into the source: a
    # password with a quote in it would otherwise be Python code.
    until python -c "
import os, sys, psycopg
try:
    psycopg.connect(os.environ['LANGGRAPH_PG_DSN'], connect_timeout=3).close()
except Exception as e:
    print(e, file=sys.stderr); sys.exit(1)
" 2>/dev/null; do
        i=$((i + 1))
        if [ "$i" -ge 60 ]; then
            echo "[entrypoint] postgres did not become reachable; starting anyway" >&2
            break
        fi
        [ "$i" = 1 ] && echo "[entrypoint] waiting for postgres..."
        sleep 2
    done
fi

# 4. The sandbox image. compose builds it before this container starts (the
#    sandbox-image service); this is the fallback for a stack started with
#    --no-build, which is how the desktop app runs the pulled release images.
#    A bundle that starts without it fails on the first tool call of the
#    first task instead of at boot.
if ! docker image inspect tektonix-sandbox:latest >/dev/null 2>&1; then
    if [ -d /app/docker/agent-sandbox ]; then
        echo "[entrypoint] building the sandbox image (it was missing)..."
        docker build -q -t tektonix-sandbox:latest /app/docker/agent-sandbox >/dev/null \
            && echo "[entrypoint] sandbox image ready" \
            || echo "[entrypoint] sandbox build failed -- tasks will fail on their first command" >&2
    else
        echo "[entrypoint] no sandbox context mounted; expecting tektonix-sandbox:latest on the host" >&2
    fi
fi

# 5. Whose files. The agent writes into PROJECTS_DIR, the operator's own
#    folder on the host: worktrees, commits, merges. As root, every one of
#    them is root-owned on Linux. With PUID/PGID set in .env (`id -u`,
#    `id -g`) the server runs as that user, after the volumes it writes are
#    made its own (a release that ran as root left them root-owned) and with
#    the docker socket's group, which is how it starts sandbox containers.
#    Unset, it stays root: Docker Desktop's bind mounts do not care, and
#    that is every install before 2026-09-29.
puid=${PUID:-0}
pgid=${PGID:-0}
if [ "$puid" != 0 ] && [ "$(id -u)" = 0 ]; then
    getent group "$pgid" >/dev/null || groupadd -g "$pgid" tektonix
    getent passwd "$puid" >/dev/null || useradd -u "$puid" -g "$pgid" -M -d "$state" -s /usr/sbin/nologin tektonix
    for d in "$state" "$shared" /app/logs /app/router-config /app/keys; do
        [ -d "$d" ] && chown -R "$puid:$pgid" "$d"
    done
    sock=${DOCKER_SOCKET:-/var/run/docker.sock}
    groups=--clear-groups
    [ -S "$sock" ] && groups="--groups $(stat -c %g "$sock")"
    export HOME="$state"
    echo "[entrypoint] dashboard on http://localhost:${API_PORT:-8100}"
    exec setpriv --reuid="$puid" --regid="$pgid" $groups \
        uvicorn agent.server:app --host 0.0.0.0 --port "${API_PORT:-8100}"
fi

echo "[entrypoint] dashboard on http://localhost:${API_PORT:-8100}"
exec uvicorn agent.server:app --host 0.0.0.0 --port "${API_PORT:-8100}"
