"""Hands the finished diff off to an external review service rather than
re-implementing review here: an independent, adversarial check (fresh
worktree off live's current HEAD, full CI-mirroring check suite, churn
detection, persistent history). The graph's own step-level checks stay
deterministic; this is the real pre-merge gate.
"""

import asyncio
import logging
import os
import subprocess
import sys

import httpx

from agent import paths

logger = logging.getLogger("tektonix")

# audit M-5: these are fixed localhost ports, not derived from config. The
# former REVIEW_GATE_BASE_URL env var was mandatory at startup yet read
# nowhere (it can't express both the 4100 status port and the 4101 control
# port anyway), so it was dropped rather than left as a misleading dead knob.
REVIEW_CONTROL_PORT = 4101  # localhost-only on a host install
REVIEW_SERVICE_PORT = 4100

# The host half, which is 127.0.0.1 everywhere except the container bundle:
# there the review services are sibling containers with their own names, and
# localhost is this container. Defaulting to loopback keeps a host install
# exactly as it was, including the "localhost-only" property of the control
# port -- in the bundle that property is provided by the compose network
# instead, which publishes neither port.
import os as _os_early

REVIEW_SERVICE_HOST = _os_early.environ.get("REVIEW_SERVICE_HOST", "127.0.0.1")
REVIEW_CONTROL_HOST = _os_early.environ.get("REVIEW_CONTROL_HOST", REVIEW_SERVICE_HOST)

# audit C-4: the mutating control endpoints now require this shared secret.
# Read from the agent's own env (load_dotenv in config.py). The check process
# does NOT have it (C-2 env allow-list), so a rewritten npm script can't forge
# these calls; only this server-side client and the authenticated dashboard
# (via nginx injection) can.
import os as _os
# audit H3: when this is unset the agent sends no header, the review service
# rejects the call, and every merge fails after the whole build has been paid
# for -- with nothing naming the cause. It is generated by install.sh and
# documented in .env.example now; this warns loudly if a hand-rolled install
# still lacks it.
if not _os.environ.get("REVIEW_CONTROL_SECRET"):
    logging.getLogger("tektonix").warning(
        "REVIEW_CONTROL_SECRET is not set: merge and deploy calls to the review "
        "service will be rejected. Generate one and put the SAME value in this "
        "app's .env and in services/shared/.env (see .env.example).")

_CONTROL_HEADERS = (
    {"X-Review-Secret": _os.environ["REVIEW_CONTROL_SECRET"]}
    if _os.environ.get("REVIEW_CONTROL_SECRET") else {}
)


async def trigger_check(project: str) -> dict:
    async with httpx.AsyncClient(timeout=15) as client:
        r = await client.post(f"http://{REVIEW_CONTROL_HOST}:{REVIEW_CONTROL_PORT}/check/{project}", headers=_CONTROL_HEADERS)
        r.raise_for_status()
        return r.json()


# Cached because the settings page and every poll ask the same question, and
# the answer changes only when someone edits a project's configuration.
_CHECKS_CACHE: dict[str, tuple[float, dict]] = {}
_CHECKS_TTL_S = 60


async def project_checks(force: bool = False) -> dict[str, dict]:
    """How many checks each project runs, by name, from the reviewer.

    The agent cannot answer this itself: `checks` live in projects.json's
    review section and in the review service's own built-ins, neither of
    which this process reads. Returns {} when the reviewer cannot be reached
    -- callers treat that as "cannot confirm", which is not the same as
    "none", and must fail safe rather than assume.
    """
    import time as _time
    cached = _CHECKS_CACHE.get("all")
    if cached and not force and _time.monotonic() - cached[0] < _CHECKS_TTL_S:
        return cached[1]
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.get(f"http://{REVIEW_CONTROL_HOST}:{REVIEW_CONTROL_PORT}/projects", headers=_CONTROL_HEADERS)
        if r.status_code != 200:
            logger.warning("project_checks: reviewer answered %s", r.status_code)
            return {}
        projects = r.json().get("projects") or {}
    except Exception as e:  # noqa: BLE001 -- unreachable is a "cannot confirm", not a crash
        logger.warning("project_checks: reviewer unreachable (%s)", str(e)[:120])
        return {}
    _CHECKS_CACHE["all"] = (_time.monotonic(), projects)
    return projects


async def project_has_checks(project: str) -> bool | None:
    """True / False / None when it cannot be confirmed."""
    projects = await project_checks()
    if not projects:
        return None
    entry = projects.get(project)
    if entry is None:
        return None
    return bool(entry.get("checks"))


def _reviewed_sha_is(got: str | None, expect: str) -> bool:
    """The review we are waiting for, not a neighbour that shares a prefix.

    lastReviewedSha used to be matched on the first 12 hex characters. Two
    commits in the same repo can share that prefix; accepting the wrong
    verdict would ship a since-changed diff as if it had been reviewed.
    Full-string equality is the claim wait_for_review's docstring already
    makes. Empty values never match.
    """
    if not got or not expect:
        return False
    return got == expect


async def _read_state(project: str) -> dict | None:
    async with httpx.AsyncClient(timeout=15) as client:
        r = await client.get(f"http://{REVIEW_SERVICE_HOST}:{REVIEW_SERVICE_PORT}/api/review/status")
        r.raise_for_status()
        return r.json().get(project)


async def wait_for_review(project: str, expect_sha: str, timeout: int = 900, poll_interval: int = 5) -> dict:
    """Polls until the review service has reviewed `expect_sha` specifically,
    not just any review -- a stale result for an older sha would otherwise
    silently pass a since-changed diff. Raises TimeoutError past `timeout`.

    A single transient poll failure (connection refused, a 500) is treated
    as "not ready yet" rather than aborting the wait, since the review
    service can be mid-restart when a poll lands. Sustained failure still
    hits the same timeout as before.
    """
    elapsed = 0
    while elapsed < timeout:
        try:
            state = await _read_state(project)
        except httpx.HTTPError as e:
            logger.warning("wait_for_review: transient poll failure for %s (will retry): %s", project, e)
            state = None
        if state and _reviewed_sha_is(state.get("lastReviewedSha"), expect_sha):
            return state
        await asyncio.sleep(poll_interval)
        elapsed += poll_interval
    raise TimeoutError(f"review service did not review {expect_sha[:12]} within {timeout}s")


async def merge_and_deploy(project: str) -> dict:
    """Only called after wait_for_review returns a ready verdict. Not
    re-verified here: the review service's own merge endpoint re-gates on
    current review state server-side, so a stale or incorrect call fails
    closed rather than merging silently.
    """
    async with httpx.AsyncClient(timeout=30) as client:
        # audit M-27: BOTH endpoints deliberately return meaningful JSON on
        # non-2xx (merge: 409 {reason}; restart: 500 {stage: "build"|"restart"}),
        # so we must NOT raise_for_status-and-discard. The actual bug is a body
        # that is NOT JSON at all -- an nginx 502 or an HTML 500 -- whose .json()
        # raised JSONDecodeError up into the caller's committed_sha-losing
        # escalation path (C-6), possibly after a partial merge. So: parse JSON,
        # and only synthesize a stage error when the body cannot be decoded.
        merge_res = await client.post(f"http://{REVIEW_SERVICE_HOST}:{REVIEW_SERVICE_PORT}/api/projects/{project}/merge", json={}, headers=_CONTROL_HEADERS)
        try:
            merge_body = merge_res.json()
        except ValueError:
            return {"ok": False, "stage": "merge",
                    "error": f"merge returned a non-JSON {merge_res.status_code} body: {merge_res.text[:200]!r}"}
        if not merge_body.get("ok"):
            # local "stage" AFTER the spread so a remote body can't override our
            # determination that this failed at the merge step.
            return {"ok": False, **merge_body, "stage": "merge"}

        restart_res = await client.post(
            f"http://{REVIEW_SERVICE_HOST}:{REVIEW_SERVICE_PORT}/api/projects/{project}/restart", json={}, headers=_CONTROL_HEADERS, timeout=180
        )
        try:
            restart_body = restart_res.json()
        except ValueError:
            # Merge already succeeded; the build/restart is what failed. A
            # non-JSON body here is infra (proxy/process), i.e. a "restart" stage.
            return {"ok": False, "stage": "restart",
                    "error": f"restart returned a non-JSON {restart_res.status_code} body: {restart_res.text[:200]!r}"}
        if not restart_body.get("ok"):
            # Preserve the remote's own stage ("build" vs "restart") -- that is
            # what verify_and_ship uses to loop back on a real compile error
            # instead of escalating -- but default to "restart" if absent.
            stage = restart_body.get("stage", "restart")
            return {"ok": False, **restart_body, "stage": stage}

        # A merged-and-deployed commit may have changed the repo's structure,
        # and the codebase map is what planning sessions and build tasks use
        # to orient (agent/cartographer.py). The nightly-turned-half-hourly
        # cron already bounds staleness for commits landing any other way
        # (manual, reviewer auto-merge); this closes the gap to ~zero for the
        # ships THIS process makes. Fire-and-forget detached subprocess, not
        # an in-loop task: the cartographer's model call can take minutes and
        # must never couple to this node's lifetime or the server's event
        # loop -- and NOT --force, so a merge that changed no structure costs
        # a pure-Python tree walk and no model call (the hash gate decides).
        # The review service pushes the merged base branch to origin itself,
        # but with `git push origin` and no credentials -- which works for an
        # SSH origin carrying a deploy key and fails for an HTTPS one. A
        # cloned project has exactly that: an https remote with nothing on it,
        # because the token is deliberately never written into .git/config.
        #
        # So the push it could not do happens here, where the token lives. The
        # merge already happened and is not being rolled back, so this is
        # reported rather than allowed to fail the ship -- same posture the
        # review service takes.
        pushed = await _push_https_origin_if_needed(project)
        out = {"ok": True, "merge": merge_body, "restart": restart_body}
        if pushed is not None:
            out["origin_push"] = pushed

        _refresh_codebase_map(project)
        return out


async def _push_https_origin_if_needed(project: str) -> dict | None:
    """Push the base branch to an https origin the review service could not.

    None when there is nothing to do: no origin, an SSH origin (a deploy key
    already carries it), or no token. Never raises.
    """
    from agent.config import PROJECTS, load_config  # noqa: PLC0415
    from agent.tools.git import _git  # noqa: PLC0415
    from agent import github_settings  # noqa: PLC0415

    cfg = PROJECTS.get(project) or {}
    live = cfg.get("live")
    if not live:
        return None
    base = cfg.get("base_branch") or "main"

    configured = await _git("config --local --get remote.origin.url", live, timeout=15)
    origin = configured["output"].strip() if configured["ok"] else ""
    if not origin.startswith("https://"):
        return None

    from agent.tools import github_tools  # noqa: PLC0415

    slug = github_tools.repo_slug_from_remote(origin)
    if not slug:
        return {"ok": False, "reason": "origin is https but not a GitHub URL"}

    cfg_obj = load_config()
    try:
        token = github_settings.token_for(github_settings.current(), cfg_obj, project)
    except Exception:  # noqa: BLE001
        token = getattr(cfg_obj, "github_token", None)
    if not token:
        return {"ok": False, "reason": "no GitHub token, so origin stays behind"}

    r = await _git(f"push https://x-access-token:{token}@github.com/{slug}.git {base}",
                   live, timeout=300)
    if not r["ok"]:
        return {"ok": False, "reason": r["output"].replace(token, "***")[:200]}
    return {"ok": True, "pushed": base}


def _refresh_codebase_map(project: str) -> None:
    """Kick a detached cartographer run for one repo; never raises, never
    blocks -- a map refresh failing must not turn a successful ship into an
    error, so the subprocess logs to the cartographer's own log and this
    only reports that the kick itself could not start."""
    try:
        # Log location follows the installation, not a fixed /var/log path a
        # non-root install could not write to.
        log_path = os.environ.get("AGENT_CARTOGRAPHER_LOG") or str(
            paths.DATA_DIR / "cartographer.log")
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, "ab") as log:
            subprocess.Popen(
                [sys.executable, str(paths.repo_path("scripts", "run_cartographer.py")), project],
                cwd=str(paths.REPO_ROOT), stdout=log, stderr=log,
                start_new_session=True,
            )
        logger.info("kicked codebase-map refresh for %s after merge+deploy", project)
    except Exception:  # noqa: BLE001 -- best-effort by design
        logger.exception("could not start post-ship cartographer for %s", project)


async def ship_as_pull_request(project: str, branch: str, sha: str, title: str) -> dict:
    """Push the task branch and open a pull request against the base branch.

    The other way to ship, for a project whose base branch the agent is not
    allowed to write. The review gate is unchanged and has already run: this is
    only what happens AFTER a pass. A person merges.

    Returns the same shape merge_and_deploy does, so the caller treats the two
    outcomes identically apart from what it tells the operator.
    """
    from agent.config import PROJECTS, load_config  # noqa: PLC0415
    from agent.tools.git import _git  # noqa: PLC0415
    from agent import github_repos  # noqa: PLC0415
    from agent.tools import github_tools  # noqa: PLC0415

    cfg = PROJECTS.get(project) or {}
    live = cfg.get("live")
    base = cfg.get("base_branch") or "main"
    if not live:
        return {"ok": False, "stage": "ship", "error": f"{project} has no live path"}

    # Per-project first, the environment second -- the same resolution the
    # GitHub inbox uses. Settings > GitHub is documented as the preferred place
    # to put a token, and a ship step that ignored it would quietly use the
    # wrong one for a project that has its own.
    from agent import github_settings  # noqa: PLC0415

    cfg_obj = load_config()
    try:
        token = github_settings.token_for(github_settings.current(), cfg_obj, project)
    except Exception:  # noqa: BLE001 -- unreadable settings must not beat the env fallback
        token = getattr(cfg_obj, "github_token", None)
    if not token:
        return {"ok": False, "stage": "ship",
                "error": "shipping as a pull request needs a GitHub token with "
                         "`pull_requests: write` -- set one in Settings > GitHub for this "
                         "project, or GITHUB_TOKEN in the environment"}

    remote = await _git("remote get-url origin", live, timeout=15)
    slug = github_tools.repo_slug_from_remote(remote["output"].strip()) if remote["ok"] else None
    if not slug:
        return {"ok": False, "stage": "ship",
                "error": f"{project} has no GitHub origin to open a pull request against"}

    # The push has to authenticate, and how depends on what the remote is.
    #
    # A project cloned from a URL has a plain https origin with no credentials
    # on it -- the token is deliberately not written into .git/config, which
    # anyone who can read the checkout can read. So the token goes on the
    # command line for this one push and nowhere else: `git push <url>` takes
    # a URL in place of a remote name, and nothing about it is stored.
    #
    # A project with an SSH origin already has a deploy key configured through
    # core.sshCommand, so the plain remote name is right and adding a token
    # would do nothing.
    configured = await _git("config --local --get remote.origin.url", live, timeout=15)
    origin = configured["output"].strip() if configured["ok"] else ""
    if origin.startswith("https://"):
        target = f"https://x-access-token:{token}@github.com/{slug}.git"
    else:
        target = "origin"

    push = await _git(f"push --quiet {target} {branch}", live, timeout=300)
    if not push["ok"]:
        # git echoes the URL it was given, token and all.
        detail = push["output"].replace(token, "***")[:300]
        return {"ok": False, "stage": "ship",
                "error": f"could not push {branch}: {detail}"}

    try:
        pr = await github_repos.open_pull_request(
            token, slug, head=branch, base=base, title=title,
            body=f"Opened by Tektonix for task branch `{branch}` at `{sha[:12]}`.\n\n"
                 f"The automated review gate passed before this was opened.",
        )
    except (PermissionError, LookupError, ValueError) as e:
        return {"ok": False, "stage": "ship", "error": f"could not open a pull request: {e}"}

    return {"ok": True, "shipped": "pull_request", "pull_request": pr["url"],
            "number": pr["number"], "branch": branch}
